server:
  port: 11113

spring:
  application:
    name: DebeziumApp3
  datasource:
    url: jdbc:postgresql://localhost:5558/destination_db
    password: postgres
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
